/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ssinghal' at '4/22/15 11:07 AM' with Gradle 2.3
 *
 * @author ssinghal, @date 4/22/15 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
